# Generated by Django 4.2 on 2023-04-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField()),
                ('season_id', models.IntegerField()),
                ('div_name', models.CharField(max_length=64)),
                ('map', models.CharField(max_length=64)),
                ('winner', models.IntegerField()),
                ('winner_score', models.IntegerField()),
                ('loser_score', models.IntegerField()),
                ('team_1', models.IntegerField()),
                ('team_2', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.IntegerField()),
                ('div_id', models.IntegerField()),
                ('div_name', models.CharField(max_length=64)),
                ('team_id', models.IntegerField()),
                ('player_id', models.CharField(max_length=20)),
                ('player_name', models.CharField(max_length=64)),
            ],
        ),
    ]
