# Generated by Django 4.2 on 2023-04-12 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0003_seasontotal_delete_matches_delete_players'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seasontotal',
            old_name='backstabds',
            new_name='backstabs',
        ),
    ]
