# Generated by Django 4.2 on 2023-04-12 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0004_rename_backstabds_seasontotal_backstabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seasontotal',
            name='team_id',
        ),
    ]
