# Generated by Django 4.2 on 2023-04-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0005_remove_seasontotal_team_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seasontotal',
            name='games_played',
            field=models.IntegerField(),
        ),
    ]
