# Generated by Django 4.2 on 2023-04-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboards', '0006_alter_seasontotal_games_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='seasontotal',
            name='class_played',
            field=models.CharField(default='all', max_length=32),
        ),
    ]
